# -*- coding: utf-8 -*-
"""ProvaPython.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yiN8mLu-Z6dmqC2U65C1AMobZEcedn37

Rock paper scissors game
"""



import streamlit as st
import random

# Dizionari per le scelte
scelta_utente_in_numeri = {
    "rock": 1,
    "paper": 2,
    "scissor": 3
}

scelta_numero_computer = {
    1: "rock",
    2: "paper",
    3: "scissor"
}

# Titolo dell'app
st.title("Gioco: Sasso, Carta, Forbice")

# Input dell'utente
question = st.selectbox("Scegli tra Rock, Paper o Scissor:", ["rock", "paper", "scissor"])
st.write("Hai scelto:", question)

# Scelta casuale del computer
scelta_computer = scelta_numero_computer[random.randint(1, 3)]
st.write("Il computer ha scelto:", scelta_computer)

# Logica del gioco
if scelta_utente_in_numeri[question] == scelta_utente_in_numeri[scelta_computer]:
    st.write("Pareggio!")
elif (scelta_utente_in_numeri[question] == 1 and scelta_computer == "paper") or \
     (scelta_utente_in_numeri[question] == 2 and scelta_computer == "scissor") or \
     (scelta_utente_in_numeri[question] == 3 and scelta_computer == "rock"):
    st.write("Hai perso!")
else:
    st.write("Hai vinto!")