# -*- coding: utf-8 -*-
"""ProvaPython.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yiN8mLu-Z6dmqC2U65C1AMobZEcedn37

Rock paper scissors game
"""



import random

scelta_utente_in_numeri = {
    "rock" : 1,
    "paper" : 2,
    "scissor" : 3
}

scelta_computer = random.randint(1,3)

question = input("You have to choose between Rock, paper or scissor ").lower()
print("You have choosen", question)

scelta_numero_computer = {
    1 : "rock",
    2 : "paper",
    3 : "scissor"
}

scelta_computer = scelta_numero_computer[scelta_computer]
print("Computer has choosen", scelta_computer)

if scelta_utente_in_numeri[question] == scelta_computer:
    print("It's a tie")
elif (scelta_utente_in_numeri[question] == 1 and scelta_computer == "paper") or (scelta_utente_in_numeri[question] == 2 and scelta_computer == "scissor") or (scelta_utente_in_numeri[question] == 3 and scelta_computer == "rock"):
    print("You lost")
else:
    print("You won")